modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
# issueTrackerURL="https://github.com/Negodya1/Create-Vintage-Improvements/issues" #optional
[[mods]] #mandatory
    modId="vintage_kubejs"
    version="1.19.2-1.0.0rc"
    displayName="Vintage KubeJS" #mandatory
    # displayURL="https://github.com/Negodya1/Create-Vintage-Improvements" #optional
    logoFile="logo.png"
    # A text field displayed in the mod UI
    credits="reds - major coding help"
    # A text field displayed in the mod UI
    authors="Negodya1" #optional
    description="KubeJS support for Create: Vintage Improvements"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.vintage_kubejs]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vintage_kubejs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vintage_kubejs]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,)"
    ordering="NONE"
    side="BOTH"