modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    namespace="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    #displayURL="https://github.com/Negodya1/Create-Vintage-Improvements"
    #issueTrackerURL="https://github.com/Negodya1/Create-Vintage-Improvements/issues"
    logoFile="logo.png"
    credits='''reds - major coding help'''
    authors="${mod_authors}"
    #displayTest="MATCH_VERSION"

description="${mod_description}"

[[dependencies.vintage_kubejs]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.vintage_kubejs]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.vintage_kubejs]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vintage_kubejs]]
    modId="vintageimprovements"
    mandatory=true
    versionRange="[0.2.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vintage_kubejs]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[2001.6.4-build.95,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.vintage_kubejs]]
    modId = "kubejs_create"
    mandatory = true
    versionRange = "[2001.2.5-build.2,)"
    ordering = "AFTER"
    side = "BOTH"